import type { Metadata, Viewport } from 'next';
import { Analytics } from '@vercel/analytics/react';
import './globals.css';

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
};

export const metadata: Metadata = {
  metadataBase: new URL('https://threadstomillions.com'),
  title: {
    default: 'Threads to Millions - Grow and Monetize Your Threads Audience',
    template: '%s | Threads to Millions',
  },
  description:
    'Join 10,000+ creators using the proven STAR Method to grow and monetize on Threads. Learn content strategies, engagement tactics, and monetization frameworks from Lexie (@getdigitalwithlexie).',
  keywords: [
    'Threads',
    'Threads app',
    'make money on Threads',
    'Threads monetization',
    'grow on Threads',
    'Threads strategy',
    'Threads algorithm',
    'Threads tips',
    'Threads growth',
    'social media monetization',
    'content creator course',
    'Threads to Millions',
    'STAR Method',
    'Lexie Threads',
    'getdigitalwithlexie',
    'how to grow on Threads',
    'Threads for business',
    'Threads engagement',
    'Threads content strategy',
    'monetize social media',
  ],
  authors: [{ name: 'Lexie', url: 'https://www.threads.net/@getdigitalwithlexie' }],
  creator: 'Lexie (@getdigitalwithlexie)',
  publisher: 'Threads to Millions',
  alternates: {
    canonical: 'https://threadstomillions.com',
  },
  robots: {
    index: true,
    follow: true,
    'max-image-preview': 'large',
    'max-snippet': -1,
    'max-video-preview': -1,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },
  icons: {
    icon: '/favicon.ico',
    apple: '/apple-touch-icon.png',
  },
  openGraph: {
    url: 'https://threadstomillions.com',
    type: 'website',
    siteName: 'Threads to Millions',
    locale: 'en_US',
    title: 'Threads to Millions - Grow and Monetize Your Threads Audience',
    description:
      'Join 10,000+ creators using the proven STAR Method to grow and monetize on Threads. $2M+ revenue generated by community members.',
    images: [
      {
        url: '/og-image-v6.jpg',
        width: 1200,
        height: 630,
        alt: 'Threads to Millions - Master the Threads Algorithm and Monetize Your Audience',
        type: 'image/jpeg',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Threads to Millions - Grow and Monetize Your Threads Audience',
    description:
      'Join 10,000+ creators using the proven STAR Method to grow and monetize on Threads. $2M+ revenue generated by community members.',
    images: ['/og-image-v6.jpg'],
    creator: '@getdigitalwithlexie',
  },
  category: 'education',
};

const jsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'Organization',
      '@id': 'https://threadstomillions.com/#organization',
      name: 'Threads to Millions',
      url: 'https://threadstomillions.com',
      logo: {
        '@type': 'ImageObject',
        url: 'https://threadstomillions.com/og-image-v6.jpg',
        width: 1200,
        height: 630,
      },
      founder: {
        '@type': 'Person',
        name: 'Lexie',
        alternateName: 'getdigitalwithlexie',
        url: 'https://www.threads.net/@getdigitalwithlexie',
      },
      sameAs: [
        'https://www.threads.net/@getdigitalwithlexie',
      ],
      description:
        'Threads to Millions is a community and course by Lexie teaching creators how to grow and monetize on the Threads social media platform using the proven STAR Method.',
    },
    {
      '@type': 'WebSite',
      '@id': 'https://threadstomillions.com/#website',
      url: 'https://threadstomillions.com',
      name: 'Threads to Millions',
      publisher: {
        '@id': 'https://threadstomillions.com/#organization',
      },
      description:
        'The proven roadmap to turn your content into conversions on Threads — without feeling spammy or salesy.',
    },
    {
      '@type': 'Course',
      '@id': 'https://threadstomillions.com/#course',
      name: 'Threads to Millions',
      description:
        'A comprehensive community and course teaching creators how to grow their Threads audience and monetize their content using the STAR Method. Includes step-by-step courses, weekly live calls, AI-powered tools, and a private community of 10,000+ members.',
      provider: {
        '@id': 'https://threadstomillions.com/#organization',
      },
      instructor: {
        '@type': 'Person',
        name: 'Lexie',
        alternateName: 'getdigitalwithlexie',
      },
      url: 'https://nomadproin90days.com/shop/d8beb61f-33df-4306-a897-87b3a1ffe197',
      image: 'https://threadstomillions.com/og-image-v6.jpg',
      offers: {
        '@type': 'Offer',
        url: 'https://nomadproin90days.com/shop/d8beb61f-33df-4306-a897-87b3a1ffe197',
        availability: 'https://schema.org/InStock',
        category: 'Online Course',
      },
      hasCourseInstance: {
        '@type': 'CourseInstance',
        courseMode: 'online',
        courseWorkload: 'Self-paced',
      },
      about: [
        'Threads social media growth',
        'Content monetization',
        'STAR Method',
        'Social media marketing',
      ],
      aggregateRating: {
        '@type': 'AggregateRating',
        ratingValue: '4.9',
        ratingCount: '10000',
        bestRating: '5',
        worstRating: '1',
      },
    },
    {
      '@type': 'FAQPage',
      '@id': 'https://threadstomillions.com/#faq',
      mainEntity: [
        {
          '@type': 'Question',
          name: 'What is Threads to Millions?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'Threads to Millions (TTM) is a community and course created by Lexie (@getdigitalwithlexie) that teaches creators how to grow their audience and monetize on the Threads social media platform. It includes step-by-step courses, weekly live calls, AI-powered tools like ThreadyBot, and a private community of over 10,000 members.',
          },
        },
        {
          '@type': 'Question',
          name: 'What is the STAR Method?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'The STAR Method is the core methodology taught in Threads to Millions. It stands for: Story First (lead with your personal transformation), Teach for Free (give your best advice without asking for anything), 80/20 Engagement Rule (spend 80% of your time engaging with others), and Sell in the Downthread (never open with a pitch — hook your audience first, then mention your offer naturally in the replies).',
          },
        },
        {
          '@type': 'Question',
          name: 'Can you really make money on Threads?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'Yes. Threads to Millions members have collectively generated over $2 million in revenue. The founder Lexie herself earns 5 figures a month from Threads. The community teaches proven strategies for monetizing your Threads presence through content creation and authentic engagement.',
          },
        },
        {
          '@type': 'Question',
          name: 'How much does Threads to Millions cost?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'Threads to Millions offers flexible membership options with a 30-day money-back guarantee. You can cancel anytime and get instant access to all courses, the private community, weekly live calls, and the ThreadyBot AI assistant.',
          },
        },
        {
          '@type': 'Question',
          name: 'Do I need a large following to get started?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'Not at all. Lexie started without a massive following or a marketing degree. The TTM strategies are designed for creators at any level. Members have seen an average of 500% growth in their Threads following using the methods taught in the community.',
          },
        },
      ],
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="font-body antialiased">
        {children}
        <Analytics />
      </body>
    </html>
  );
}
