"use client";

import Link from 'next/link';
import { motion } from "framer-motion";
import { ShieldCheck, Mail, MapPin } from 'lucide-react';

const Footer = () => {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="py-20 border-t border-border bg-card/30">
      <div className="container mx-auto px-6">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-12 mb-16">
          {/* Brand & Mission */}
          <div className="md:col-span-2">
            <Link href="/" className="flex items-center gap-2 mb-6">
              <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-primary to-accent flex items-center justify-center shadow-lg shadow-primary/20">
                <span className="text-primary-foreground font-bold text-lg italic">T</span>
              </div>
              <span className="font-display text-2xl font-bold uppercase tracking-tight">
                Threads<span className="text-primary italic">To</span>Millions
              </span>
            </Link>
            <p className="text-muted-foreground text-lg leading-relaxed max-w-md">
              The premier community and education platform for creators mastering the Threads algorithm. $2M+ generated by our members using the STAR Method.
            </p>
          </div>

          {/* Quick Links */}
          <div>
            <h4 className="font-display font-bold text-foreground mb-6 uppercase tracking-wider text-sm">Resources</h4>
            <ul className="space-y-4 text-muted-foreground">
              <li><Link href="/blog" className="hover:text-primary transition-colors">Masterclass Blog</Link></li>
              <li><Link href="/free-lead-magnet" className="hover:text-primary transition-colors">Free Growth Guide</Link></li>
              <li><Link href="/#strategy" className="hover:text-primary transition-colors">The STAR Method</Link></li>
              <li><Link href="/#testimonials" className="hover:text-primary transition-colors">Success Stories</Link></li>
            </ul>
          </div>

          {/* Trust & Support */}
          <div>
            <h4 className="font-display font-bold text-foreground mb-6 uppercase tracking-wider text-sm">Trust & Support</h4>
            <ul className="space-y-4 text-muted-foreground">
              <li><Link href="/contact" className="hover:text-primary transition-colors flex items-center gap-2"><Mail className="w-4 h-4" /> Contact Support</Link></li>
              <li><Link href="/privacy" className="hover:text-primary transition-colors">Privacy Policy</Link></li>
              <li><Link href="/terms" className="hover:text-primary transition-colors">Terms of Service</Link></li>
              <li className="flex items-center gap-2 text-xs pt-2">
                <ShieldCheck className="w-4 h-4 text-primary" />
                <span>Verified Secure Checkout</span>
              </li>
            </ul>
          </div>
        </div>

        <div className="pt-12 border-t border-border/50 flex flex-col md:flex-row items-center justify-between gap-8 text-sm text-muted-foreground">
          <div className="flex flex-col md:flex-row items-center gap-4 md:gap-8">
            <div className="flex items-center gap-2">
              <MapPin className="w-4 h-4" />
              <span>Lexie Media LLC • Delaware, USA</span>
            </div>
            <div>© {currentYear} Threads to Millions. All rights reserved.</div>
          </div>
          <div className="flex items-center gap-6">
            <a href="https://threads.net/@getdigitalwithlexie" target="_blank" rel="noopener noreferrer" className="hover:text-primary transition-colors">Threads</a>
            <a href="https://instagram.com/getdigitalwithlexie" target="_blank" rel="noopener noreferrer" className="hover:text-primary transition-colors">Instagram</a>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
